import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { callReports } from './schema';
import 'dotenv/config';

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const now = new Date();

const seeds = [
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-01'),
    customerName: 'Accra Foods Ltd',
    telephone: '0244123456',
    location: 'Tema, Accra',
    product: 'Bottled Water',
    buyerType: 'Bulk buyer',
    comments: 'Customer placed a large order for their hotel chain.',
    summary: 'Follow up on delivery schedule.',
    followUpDate: new Date('2026-06-28'),
    followedUpBy: 'Kofi Mensah',
    status: 'Pending',
    createdBy: 'Kofi Mensah',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-05'),
    customerName: 'Kumasi Supermart',
    telephone: '0201987654',
    location: 'Adum, Kumasi',
    product: 'Sachet Water',
    buyerType: 'Medium scale',
    comments: 'Interested in weekly delivery contract.',
    summary: 'Send quotation by end of week.',
    followUpDate: new Date('2026-06-30'),
    followedUpBy: 'Ama Darko',
    status: 'New',
    createdBy: 'Ama Darko',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-08'),
    customerName: 'GoldStar Filling Station',
    telephone: '0551234567',
    location: 'Sunyani',
    product: 'Bottled Water, Dispenser',
    buyerType: 'Small scale',
    comments: 'Needs dispenser for staff canteen.',
    summary: 'Dispenser demo arranged for next visit.',
    followUpDate: new Date('2026-07-02'),
    followedUpBy: 'Kwame Asante',
    status: 'Pending',
    createdBy: 'Kwame Asante',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-10'),
    customerName: 'Takoradi Port Authority',
    telephone: '0302456789',
    location: 'Takoradi',
    product: 'Bottled Water',
    buyerType: 'Bulk buyer',
    comments: 'Monthly supply for port workers. Already approved by procurement.',
    summary: 'Contract signed. First delivery done.',
    followUpDate: null,
    followedUpBy: 'Ama Darko',
    status: 'Completed',
    createdBy: 'Ama Darko',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-12'),
    customerName: 'Ho Poly Cafeteria',
    telephone: '0363001234',
    location: 'Ho, Volta Region',
    product: 'Sachet Water',
    buyerType: 'Medium scale',
    comments: 'Student cafeteria. High volume during term time.',
    summary: 'Agreed on 500 bags per week. Invoice sent.',
    followUpDate: null,
    followedUpBy: 'Kofi Mensah',
    status: 'Completed',
    createdBy: 'Kofi Mensah',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-15'),
    customerName: 'Barnor Clinic',
    telephone: '0277654321',
    location: 'East Legon, Accra',
    product: 'Bottled Water, Dispenser',
    buyerType: 'Small scale',
    comments: 'Needs bottled water for waiting room and dispenser for staff area.',
    summary: 'Quoted GHS 1,800 for initial setup.',
    followUpDate: new Date('2026-06-27'),
    followedUpBy: 'Kwame Asante',
    status: 'New',
    createdBy: 'Kwame Asante',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-17'),
    customerName: 'Koforidua Business School',
    telephone: '0340556677',
    location: 'Koforidua',
    product: 'Sachet Water, Bottled Water',
    buyerType: 'Bulk buyer',
    comments: 'Annual supply tender. Competing with two other suppliers.',
    summary: 'Tender submission deadline June 30.',
    followUpDate: new Date('2026-06-29'),
    followedUpBy: 'Ama Darko',
    status: 'Pending',
    createdBy: 'Ama Darko',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-19'),
    customerName: 'Osei Brothers Trading',
    telephone: '0209871234',
    location: 'Techiman',
    product: 'Sachet Water',
    buyerType: 'Bulk buyer',
    comments: 'Distributor covering Brong-Ahafo region. Very high volume potential.',
    summary: 'Distributor agreement under review by management.',
    followUpDate: new Date('2026-07-05'),
    followedUpBy: 'Kofi Mensah',
    status: 'Reviewed',
    createdBy: 'Kofi Mensah',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-21'),
    customerName: 'Phoebe Event Centre',
    telephone: '0244556788',
    location: 'Spintex, Accra',
    product: 'Bottled Water',
    buyerType: 'Medium scale',
    comments: 'Regular events venue. Needs stock for weddings and conferences.',
    summary: 'Standing order of 200 cartons per event agreed.',
    followUpDate: null,
    followedUpBy: 'Kwame Asante',
    status: 'Completed',
    createdBy: 'Kwame Asante',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    date: new Date('2026-06-23'),
    customerName: 'Nana Ama Chop Bar',
    telephone: '0558123456',
    location: 'Kejetia, Kumasi',
    product: 'Sachet Water',
    buyerType: 'Small scale',
    comments: 'Small chop bar, buys 10 bags a week. Wants better pricing.',
    summary: 'Offered loyalty discount after 3 months.',
    followUpDate: new Date('2026-07-01'),
    followedUpBy: 'Ama Darko',
    status: 'New',
    createdBy: 'Ama Darko',
    createdAt: now,
    updatedAt: now,
  },
];

async function seed() {
  console.log('Seeding database...');
  await db.insert(callReports).values(seeds);
  console.log(`✓ Inserted ${seeds.length} call reports`);
  await client.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
